/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package micronaut.starter.kit;


import io.micronaut.context.ApplicationContext;
import org.dom4j.DocumentException;

public class App {
    public static void main(String[] args) {
        ApplicationContext ctx = ApplicationContext.run();
        FlowParser flowParser = ctx.getBean(FlowParser.class);
        ArgumentBean argument = ctx.getBean(ArgumentBean.class).build(args);
        PDFParser pdfParser = ctx.getBean(PDFParser.class);
        MarkdownProcessor markdownProcessor = ctx.getBean(MarkdownProcessor.class);
        try {
            // step 1: parse input xml file to markdown string
            flowParser.parse(argument.inPath + "/" + argument.inFile);
            // step 2: generate markdown content
            String markdownContent = markdownProcessor.toMarkdownFile();
            //step 3 convert to pdf
            pdfParser.toPDF(markdownContent);
        } catch(DocumentException docEx){
            System.out.println(docEx.getMessage());
        }
    }
}
